[package]
name = "gameboy-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
prettytable-rs = { version = "0.10.0", optional = true }
sdl2 = { version = "0.37.0" }

[features]
debug = ["dep:prettytable-rs"]
